export const productsData = [
  {
    id: 1,
    title: "Tomato",
    quantity: 1,
    description: "pure grocery",
    image: "./photos/Tomato.jpg",
    availablePackings: ["3Kg", "5Kg"],
    price: 1,
  },
  {
    id: 2,
    title: "Green beans",
    image: "./photos/Green beans.jpg",
    quantity: 1,
    description: "pure grocery",
    availablePackings: ["1Kg", "2Kg"],
    price: 4,
  },
  {
    id: 3,
    title: "Broccoli",
    image: "./photos/Broccoli.jpg",
    quantity: 1,
    description: "pure grocery",
    availablePackings: ["1Kg", "5Kg"],
    price: 5,
  },
  {
    id: 4,
    title: "Eggplant",
    image: "./photos/Eggplant.jpg",
    quantity: 1,
    description: "pure grocery",
    availablePackings: ["1Kg", "2Kg"],
    price: 5,
  },
  {
    id: 5,
    title: "Garlic",
    image: "./photos/Garlic.jpg",
    quantity: 1,
    description: "pure grocery",
    availablePackings: ["2Kg", "5Kg"],
    price: 10,
  },
  {
    id: 6,
    title: "Red peper",
    image: "./photos/Red peper.jpg",
    quantity: 1,
    description: "pure grocery",
    availablePackings: ["1Kg", "2Kg", "5Kg"],
    price: 4,
  },
  {
    id: 7,
    title: "Onion",
    image: "./photos/Onion.jpg",
    quantity: 1,
    description: "pure grocery",
    availablePackings: ["1Kg", "5Kg"],
    price: 2,
  },
  {
    id: 8,
    title: "Zucchini",
    quantity: 1,
    image: "./photos/Zucchini.jpg",
    description: "pure grocery",
    availablePackings: ["3Kg", "5Kg"],
    price: 6,
  },
];
